apiVersion: skaffold/v1beta2
kind: Config
build: 
    local: 
        push: false
    artifacts:
        - image: porzechowski/multi-client
          context: client  
          docker:
            dockerfile: Dockerfile.dev
          sync:
            '**/*.js': .
            '**/*.css': .
            '**/*.html': .
        - image: porzechowski/multi-server    
          context: server
          docker:
            dockerfile: Dockerfile.dev
          sync: 
            '**/*.js': .
        - image: porzechowski/multi-worker   
          context: worker
          docker:
            dockerfile: Dockerfile.dev
          sync: 
            '**/*.js': .
deploy:
    kubectl:
        manifests:
            - k8s/client-deployment.yaml
            - k8s/server-deployment.yaml
            - k8s/worker-deployment.yaml